const express = require('express');
const axios = require('axios');
const app = express();

app.use(express.json());

const ROBLOX_API_KEY = process.env.ROBLOX_API_KEY;

app.post('/generate-avatar-art', async (req, res) => {
    const { username, userId } = req.body;
    if (!username || !userId) return res.status(400).send('Missing data');

    try {
        // 1. جلب رابط صورة السكن الرسمية من روبلوكس
        const thumbRes = await axios.get(`https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${userId}&size=420x420&format=Png&isCircular=false`);
        const avatarUrl = thumbRes.data.data[0]?.imageUrl;

        if (!avatarUrl) return res.status(500).send('Could not fetch Roblox thumbnail');

        // 2. طلب توليد الصورة عبر Pollinations AI
        const prompt = encodeURIComponent(`Hyper-realistic 4k cinematic anime portrait of a character matching this avatar style and colors: ${avatarUrl}, detailed face, cool lighting, masterpiece`);
        const aiImageUrl = `https://image.pollinations.ai/p/${prompt}?width=512&height=512&nologo=true`;

        // جلب الصورة المولّدة كمصفوفة بيانات
        const imageBuffer = await axios.get(aiImageUrl, { responseType: 'arraybuffer' });

        // 3. تجهيز بيانات الرفع بطريقة مبسطة لتفادي خطأ 400
        const boundary = '----WebKitFormBoundary7MA4YWxkTrZu0gW';
        let payload = `--${boundary}\r\n`;
        payload += `Content-Disposition: form-data; name="request"\r\n\r\n`;
        payload += JSON.stringify({
            assetType: "Decal",
            displayName: `${username}_AI_Art`,
            description: "Generated by AI"
            // تم إزالة تعقيدات الـ creationContext لضمان قبول الطلب فوراً من أي حساب أو جروب
        }) + `\r\n`;
        payload += `--${boundary}\r\n`;
        payload += `Content-Disposition: form-data; name="file"; filename="art.png"\r\n`;
        payload += `Content-Type: image/png\r\n\r\n`;

        const headerBuffer = Buffer.from(payload, 'utf-8');
        const footerBuffer = Buffer.from(`\r\n--${boundary}--\r\n`, 'utf-8');
        const fullBody = Buffer.concat([headerBuffer, Buffer.from(imageBuffer.data), footerBuffer]);

        // الرفع إلى روبلوكس Open Cloud
        const uploadRes = await axios.post('https://apis.roblox.com/assets/v1/assets', fullBody, {
            headers: {
                'x-api-key': ROBLOX_API_KEY,
                'Content-Type': `multipart/form-data; boundary=${boundary}`
            }
        });

        const assetId = uploadRes.data.assetId;
        res.json({ success: true, assetId: assetId });

    } catch (error) {
        console.error(error);
        // طباعة تفاصيل الخطأ القادم من روبلوكس لمعرفته بدقة في الـ Logs إذا تكرر
        if (error.response && error.response.data) {
            console.error("Roblox API Error Details:", JSON.stringify(error.response.data));
        }
        res.status(500).json({ success: false, error: error.message });
    }
});

const listener = app.listen(process.env.PORT || 3000, () => {
    console.log("Your app is listening on port " + listener.address().port);
});
